# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# This is only needed if you are using the plugin from sources with bundler
Vagrant.require_plugin 'docker-provider'
Vagrant.require_plugin 'vagrant-cachier'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.cache.scope = :box

  # This just fires up a container with a SSH server
  config.vm.define 'dummy' do |node|
    node.vm.box = 'dummy'
    node.vm.box_url = 'http://bit.ly/vagrant-docker-dummy'

    node.vm.provider :docker do |docker|
      docker.image = 'fgrehm/vagrant-ubuntu:precise'
    end
  end

  # This is a container that gets provisioned with Puppet
  config.vm.define 'precise' do |node|
    node.vm.box = 'precise64'
    node.vm.box_url = 'http://bit.ly/vagrant-docker-precise'

    node.vm.provision :puppet do |puppet|
      puppet.manifests_path = "."
      puppet.manifest_file  = "site.pp"
    end
  end
end
