# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# This is only needed if you are using the plugin from sources with bundler
Vagrant.require_plugin 'docker-provider'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise"

  config.vm.provider :docker do |docker|
    docker.image = "fgrehm/vagrant-ubuntu:precise"
    docker.cmd   = ["/usr/sbin/sshd", "-D", "-e"]
  end

  config.vm.provision :shell, inline: %[
    echo 'hello from docker'
    # mkdir -p /vagrant/tmp
    # touch /vagrant/tmp/provisioned
  ]
end
